# Generated by Django 2.0.4 on 2018-11-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('deadline', models.DateField()),
                ('data_type', models.IntegerField(choices=[(1, 'Image'), (2, 'Text'), (3, 'Audio')])),
                ('task_type', models.IntegerField(choices=[(1, 'Image boundbox'), (2, 'Image classification'), (3, 'Text classification'), (4, 'Audio classification'), (5, 'Marker classification'), (6, 'Semantic classification')])),
                ('labels', models.CharField(max_length=200)),
                ('annotation_type', models.IntegerField(choices=[(1, 'JSON'), (2, 'XML')])),
                ('main_nitems', models.IntegerField(null=True)),
                ('dk_nitems', models.IntegerField(null=True)),
                ('number_of_tasks', models.IntegerField(null=True)),
                ('tika_score_flag', models.IntegerField(default=0, null=True)),
                ('main_file', models.FileField(null=True, upload_to='projects/')),
                ('dk_file', models.FileField(null=True, upload_to='projects/dk')),
                ('project_id', models.CharField(max_length=8, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
    ]
