# Generated by Django 2.0.4 on 2018-11-27 19:26

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tds_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='nasa_tlx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('task_id', models.CharField(max_length=250)),
                ('sitting_no', models.IntegerField(default=0)),
                ('mental_demand', models.IntegerField(default=0)),
                ('physical_demand', models.IntegerField(default=0)),
                ('temporal_demand', models.IntegerField(default=0)),
                ('performance', models.IntegerField(default=0)),
                ('effort', models.IntegerField(default=0)),
                ('frustration', models.IntegerField(default=0)),
                ('ques_1', models.IntegerField(default=0)),
                ('ques_2', models.IntegerField(default=0)),
                ('ques_3', models.IntegerField(default=0)),
                ('ques_4', models.IntegerField(default=0)),
                ('ques_5', models.IntegerField(default=0)),
                ('ques_6', models.IntegerField(default=0)),
                ('ques_7', models.IntegerField(default=0)),
                ('ques_8', models.IntegerField(default=0)),
                ('ques_9', models.IntegerField(default=0)),
                ('ques_10', models.IntegerField(default=0)),
                ('ques_11', models.IntegerField(default=0)),
                ('ques_12', models.IntegerField(default=0)),
                ('ques_13', models.IntegerField(default=0)),
                ('ques_14', models.IntegerField(default=0)),
                ('ques_15', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=8, unique=True)),
                ('nitems', models.IntegerField()),
                ('ncompleted', models.IntegerField(default=0)),
                ('tika_score_flag', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Incomplete'), (2, 'Completed'), (3, 'Rejected')])),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='tika_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=8)),
                ('user_id', models.CharField(max_length=8)),
                ('dk_accuracy', models.FloatField(default=-1, max_length=8)),
                ('dk_consistency', models.FloatField(default=-1, max_length=8)),
                ('nasa_tlx', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, null=True, size=None)),
                ('pe', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ts_tool_metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('task_id', models.CharField(max_length=250)),
                ('filename', models.CharField(default='0', max_length=250)),
                ('hover_time', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, size=None)),
                ('completion_time', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, size=None)),
                ('nclicks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, size=None)),
            ],
        ),
    ]
